/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    state?: string;
                    code?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Found */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    From?: string;
                    To?: string;
                    Limit?: number;
                    Offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DailyLogListResponse"];
                        "application/json": components["schemas"]["DailyLogListResponse"];
                        "text/json": components["schemas"]["DailyLogListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateDailyLogRequest"];
                    "text/json": components["schemas"]["CreateDailyLogRequest"];
                    "application/*+json": components["schemas"]["CreateDailyLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DailyLogResponse"];
                        "application/json": components["schemas"]["DailyLogResponse"];
                        "text/json": components["schemas"]["DailyLogResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DailyLogResponse"];
                        "application/json": components["schemas"]["DailyLogResponse"];
                        "text/json": components["schemas"]["DailyLogResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DailyLogResponse"];
                        "application/json": components["schemas"]["DailyLogResponse"];
                        "text/json": components["schemas"]["DailyLogResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorResponse"];
                        "application/json": components["schemas"]["ErrorResponse"];
                        "text/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ActivityType: "none" | "walking" | "running" | "gym" | "yoga" | "cycling" | "sports" | "other";
        CreateDailyLogRequest: {
            /** Format: date */
            logDate: string;
            /** Format: int32 */
            moodRating: number;
            /** Format: int32 */
            anxietyLevel: number;
            /** Format: int32 */
            stressLevel: number;
            /** Format: double */
            sleepHours: number;
            /** Format: int32 */
            sleepQuality: number;
            sleepDisturbances: components["schemas"]["SleepDisturbance"][] | null;
            activityType?: components["schemas"]["ActivityType"];
            /** Format: int32 */
            activityMinutes?: number | null;
            socialFrequency: components["schemas"]["SocialFrequency"];
            symptoms: components["schemas"]["Symptom"][] | null;
            notes?: string | null;
        };
        DailyLogListMeta: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            /** Format: int32 */
            total: number;
        };
        DailyLogListResponse: {
            data: components["schemas"]["DailyLogResponse"][] | null;
            meta: components["schemas"]["DailyLogListMeta"];
        };
        DailyLogResponse: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            logDate: string;
            /** Format: int32 */
            moodRating: number;
            /** Format: int32 */
            anxietyLevel: number;
            /** Format: int32 */
            stressLevel: number;
            /** Format: double */
            sleepHours: number;
            /** Format: int32 */
            sleepQuality: number;
            sleepDisturbances: components["schemas"]["SleepDisturbance"][] | null;
            activityType?: components["schemas"]["ActivityType"];
            /** Format: int32 */
            activityMinutes?: number | null;
            socialFrequency: components["schemas"]["SocialFrequency"];
            symptoms: components["schemas"]["Symptom"][] | null;
            notes?: string | null;
            createdAt: string | null;
            updatedAt: string | null;
        };
        ErrorBody: {
            code: string | null;
            message: string | null;
            details: components["schemas"]["ErrorDetail"][] | null;
        };
        ErrorDetail: {
            field: string | null;
            message: string | null;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @enum {string} */
        SleepDisturbance: "none" | "insomnia" | "nightmares" | "frequent_waking" | "early_waking";
        /** @enum {string} */
        SocialFrequency: "none" | "rare" | "occasional" | "frequent" | "daily";
        Symptom: {
            type: components["schemas"]["SymptomType"];
            /** Format: int32 */
            severity: number;
        };
        /** @enum {string} */
        SymptomType: "low_mood" | "hopelessness" | "fatigue" | "irritability" | "panic" | "restlessness" | "concentration" | "appetite_change";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
